services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.11.1
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  backend:
    build: ./marketplace-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/marketplace?schema=public"
      REDIS_URL: "redis://redis:6379"
      ELASTICSEARCH_NODE: "http://elasticsearch:9200"
      JWT_SECRET: "SEU_SEGREDO_SUPER_SECRETO"

  frontend:
    build:
      context: ./marketplace-frontend
      args:
        PUBLIC_API_URL: http://localhost:3000
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  es_data: